name: Latin Attitude
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09093
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: 'Latin Attitude, End Of the Road, Pavones, Costa Rica.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141215'
    - '#e0dee1'
    - '#4b494c'
    - '#817f82'
    - '#a2a0a3'
  brandStrength: 0.5
  lightness: 0.5708966
  saturation: 0.5625
  rhythmicContrast: 0.159695
purpose: []
