title: 'Latin Attitude, End Of the Road, Pavones, Costa Rica.'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5625
  brandStrength: 0.5
  rhythmicContrast: 0.159695
  brandColors:
    - '#141215'
    - '#e0dee1'
    - '#4b494c'
    - '#817f82'
    - '#a2a0a3'
  lightness: 0.5708966
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Latin Attitude
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0609319
layout_spectrum: 0
