layout_spectrum: 1
name: Latin Attitude
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.5708966
  saturation: 0.6464409
  rhythmicContrast: 0.159695
  brandColors:
    - '#FFFFFF'
    - '#74503D'
    - '#BAB0B5'
    - '#230E12'
    - '#96878C'
typography_spectrum: 0.4468803
